stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: raplis/rust_ml_service  
  DOCKER_IMAGE_TAG: latest
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]


before_script:
  - unset DOCKER_HOST
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  image: docker:latest
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG


deploy:
  image: docker:latest
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d -p 8080:8080 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - master
