stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: raplis/rust_ml_service  
  DOCKER_IMAGE_TAG: latest
  DOCKER_HOST: tcp://docker:2375/  # 注意修改端口号为 2375，TLS 禁用时默认端口

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build:
  image: docker:19.03
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy:
  image: docker:19.03
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d -p 8080:8080 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - master
