stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: raplis/rust_ml_service
  DOCKER_IMAGE_TAG: latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY


build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d -p 8080:8080 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - master
